name: "01 - Building Blocks"

on:
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello, World!"

jobs:
  echo-goodbye:
    runs-on: ubuntu-latest
    
    steps:
      - name: Failed step
        run: echo "I will fail exit 9"
      - name: Say hello
        run: echo "Hello, World!"